### ISSUE TITLE
Return key release is sent after dmenu closes, resulting in bugs especially on websites

### ISSUE THREAD

**Issue by klaasb** [klaasb/passdmenu#1]
Pressing Return to select the pass entry in dmenu results in a key-release event being sent to whatever application is focused next. Some websites run javascript that detects these events and usually breaks. I.e. by validating/submitting a login field or switching between user/password fields. This seems to happen before xdotool types user/pw.

This also seems to happen when using dmenu without the script, so it may not actually be something that can be fixed in passdmenu...

**Comment by Vouivre** [comment]
Hello,

I'm not sure the problem is not in passdmenu. I have written the following script:

```
#!/bin/zsh

prompt=$(echo "Email" | dmenu -p "Hello:")

xdotool type --clearmodifiers 'username'
xdotool getactivewindow key Tab
xdotool getactivewindow type --clearmodifiers "password"
```

It doesn't exactly what you do, but if you select the entry "Email", the username and password are entered in the boxes without a problem. Did I miss something or does it mean, there is something wrong in passdmenu ?

**Comment by klaasb** [comment]
Interesting. I've been testing calling various dmenu scripts with a key combination defined in the i3 config - while focusing an `xev` window. I tested dmenu_run(sh), i3-dmenu-desktop(perl), j4-dmenu-desktop(compiled) and some simple test script I wrote, which all exhibit the KeyRelease event with a Return/Esc when selecting/escaping from dmenu respectively. In fact, this also seems to happen in passdmenu when gpg-agent asks for the passphrase and one presses Return.

Such an event looks like this:

```
KeyRelease event, serial 32, synthetic NO, window 0x3800001,
    root 0x8d, subw 0x0, time 41152557, (116,427), root:(1080,449),
    state 0x10, keycode 36 (keysym 0xff0d, Return), same_screen YES,
    XLookupString gives 1 bytes: (0d) "^M"
    XFilterEvent returns: False
```

However, you are right and your script does not produce this behaviour. I'm stumped and currently do not have the time to work on this - sorry. I'll have look at this again next week.

**Comment by Vouivre** [comment]
Ok, no problem. If I can help somehow, for example with testing there is no problem.

**Comment by klaasb** [comment]
So I tested some more and this is certainly a general problem with the way most X11 applications handle a KeyPress that closes the application and not consuming the KeyRelease.

Of course it's mostly a bug in the javascript on those websites which should not do anything on a keyUp without a corresponding keyDown - but well, we can't fix all those websites and there's no reason to keep that KeyRelease around anyway.

So, how do we capture that event without any other window somehow getting it (i.e. by grabbing focus)? I thought it should be possible with [key grabbing](http://tronche.com/gui/x/xlib/input/keyboard-grabbing.html) from xlib using the python bindings, but could not get it to work.

I'll keep at it, but it may take some time - still swamped.

**Comment by carnager** [comment]
use rofi instead of dmenu. it will most likely have this fixed with next release: https://github.com/DaveDavenport/rofi/issues/167

**Comment by klaasb** [comment]
Totally awesome! I use rofi instead of dmenu for a while already, so that's great.
I had investigated this, but really couldn't find a way to do this from the python script.

**Comment by Vouivre** [comment]
I have discovered something interesting. With the browser qutebrowser there is no problem. At least with a shell script I have written. Qutebrowser is a python project. Perhaps the developper has also an idea what can be done. But as said, rofi is also a fix.

**Comment by carnager** [comment]
it also works with chrome

**Comment by klaasb** [comment]
So I switched this issue to 'enhancement' and will close it. We could provide a workaround, but I'd rather see this being fixed in other software which is either responsible for sending or mishandling this. There are workarounds (use rofi, another browser), although they might not be for everyone. In general though, it's also mishandled by the application/website - which should rather be fixed.

If anyone wants to implement a workaround however, I'm not against including it.
