### ISSUE TITLE
Use filename as username

### ISSUE THREAD

**Issue by ghost** [klaasb/passdmenu#10]
My passwords are organized by `site/username.gpg`. It'd be great if passdmenu could somehow get the option/autodetect whether the username is set this way. 

I don't know what percentage of Pass users do this, but the creator of Pass does.

Thanks for this great utility!

**Comment by klaasb** [comment]
Autodetection seems impossible. I think the best option would be to make it a special value for option --user that doesn't clash with the regex values accepted by it. The current default of taking the second "word" on the second line or the whole second line if it can't be split, is also not very intuitive and could be specified and handled better.

I don't have time to work on this in the next few weeks, but if you'll send a patch I'll make some time to review and integrate.

**Comment by klaasb** [comment]
Now possible with merged PR #12
