### ISSUE TITLE
Support user entries on different lines

### ISSUE THREAD

**Issue by pigmonkey** [klaasb/passdmenu#5]
I do not keep usernames on the second line of my pass entries, but I do prefix them with `login:` (for [passff](https://github.com/jvenant/passff) compatibility). I'd like it if passdmenu could find them.

The way I see that working is altering the `get_user_pw()` function to loop through `pass_ouput[1:]` (ignoring the first line, since it is pass convention that the first line is always the password) looking for a line that begins with any of passff's default login field names (login,user,username,id). The first line that matches is treated as the username line. If no line matches, it falls back to using the second line. That would solve my problem and not break the current behaviour.

I'd be happy with just using passff's default login field names, but it may be worth allowing the user to specify the field name as well. So if I knew that most of the time I prefix usernames with `login`, but sometimes I use `email`, I could do something like `passdmenu.py -U --login_field "login,email"` and the script would look for lines beginning with both. I'm not sure how useful that ability would be.

**Comment by klaasb** [comment]
That sounds good to me.
I don't currently have a use case and time to work on it may or may not happen, but would happily accept PRs.

For the second proposal, I would think of expanding/abstracting that a bit and allow passdmenu to extract multiple specified fields and/or a priority mechanism. Just for the user name field, when we already allow multiple options, it may not be that useful.

I actually had a use for getting completely different fields and not the password - can't remember what it was now.

**Comment by klaasb** [comment]
Solved for login/user fields.
